title: Rahim Gujjar | InfoSec & Systems Analyst
description: 3rd-Sem BSIT Std @ UOS. InfoSec & Systems Analyst, Digital Forensics & AI Automation, Orchestrator & Architect. Passionate about deconstructing complex Systems💣
author: Rahim Gujjar
url: https://rahimgujjar.github.io
baseurl: ""
default_image: "https://github.com/rahimgujjar/rahimgujjar.github.io/blob/main/favicon.png"

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
